// QA-only instrumentation; loads the unchanged non-development Unity bundles.
(()=>{
 let drawCount=0,lastGL=null,cameraEstimate=null;const textureUploads=[];const glp=window.WebGL2RenderingContext?.prototype;if(glp){
 const u4=glp.uniform4fv;glp.uniform4fv=function(loc,src,start,count){const i=start||0;if(src?.length>=i+16&&Math.abs(src[i]-.125)<.001&&Math.abs(Math.abs(src[i+5])-.2)<.001){let x=-src[i+12]/src[i],y=-src[i+13]/src[i+5];if(y>20&&y<90)cameraEstimate={x,y,t:performance.now()};}return u4.apply(this,arguments);};
 for(const name of ['drawElements','drawArrays','drawElementsInstanced','drawArraysInstanced']){const original=glp[name];glp[name]=function(...args){lastGL=this;drawCount++;return original.apply(this,args);};} for(const name of ['texImage2D','texStorage2D','compressedTexImage2D']){const original=glp[name];glp[name]=function(...args){const t=performance.now();const out=original.apply(this,args);textureUploads.push({t,api:name,args:args.slice(0,8).map(x=>typeof x==='number'?x:null),ms:performance.now()-t});return out;};}} const nativeRAF=window.requestAnimationFrame.bind(window), rows=[], intervals=[], contexts=[], uploads=[], timeline=[], keys=new Set();
 let instance,readyAt=0,last=0,lastKeyRun=0,replayToken=0,phase='startup',phaseStart=performance.now(),captureRequested=false,resetAt=performance.now();
 const Audio=window.AudioContext; const audioSources=[]; const heapSamples=[];
 if(Audio){window.AudioContext=function(...args){let c=new Audio(...args);contexts.push(c); const make=c.createBufferSource.bind(c); c.createBufferSource=()=>{const s=make(), row={created:performance.now(),started:null,ended:null,duration:null};audioSources.push(row);const start=s.start.bind(s);s.start=(...args)=>{row.started=performance.now();row.duration=s.buffer?.duration;if(s.buffer){const a=s.buffer.getChannelData(0);let peak=0;for(let i=0;i<a.length;i+=16)peak=Math.max(peak,Math.abs(a[i]));row.peak=peak;}if(window.qaArm&&row.duration>.089&&row.duration<.091){window.qaArm=false;setTimeout(()=>document.getElementById('replay').click(),100);}return start(...args);};s.addEventListener('ended',()=>row.ended=performance.now());return s;};c.addEventListener('statechange',()=>timeline.push({t:performance.now(),kind:'audio-state',state:c.state}));return c;};window.AudioContext.prototype=Audio.prototype;}
 window.requestAnimationFrame=fn=>nativeRAF(t=>{const begin=performance.now(),beforeDraws=drawCount;fn(t);const end=performance.now(); if(last && t!==last)intervals.push({t,dt:t-last,phase});last=t;rows.push({t,cpu:end-begin,draws:drawCount-beforeDraws,phase});if(drawCount>beforeDraws && window.qaObserve)window.qaObserve(lastGL,cameraEstimate,t);if(captureRequested && end-begin>1){captureRequested=false; const canvas=document.querySelector('canvas'); fetch('/qa/results',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'screenshot',name:'capture-'+Date.now()+'.png',data:canvas.toDataURL('image/png')})});}});
 window.qaLoaded=i=>{instance=i;readyAt=performance.now();phase='mainmenu'; timeline.push({kind:'ready',t:readyAt});};
 function key(code,down){if(down===keys.has(code))return; const map={KeyA:['a',65],KeyD:['d',68],KeyJ:['j',74],Space:[' ',32],ShiftLeft:['Shift',16],Escape:['Escape',27]}; const [k,n]=map[code];document.querySelector('canvas').dispatchEvent(new KeyboardEvent(down?'keydown':'keyup',{key:k,code,keyCode:n,which:n,charCode:0,location:code==='ShiftLeft'?1:0,bubbles:true,cancelable:true,shiftKey:code==='ShiftLeft'&&down}));if(down)keys.add(code);else keys.delete(code);timeline.push({t:performance.now(),kind:down?'down':'up',code});}
 window.qaInput=key;window.qaAudioSources=audioSources;
 function stop(){window.qaAdaptiveStop?.();replayToken++; for(const k of [...keys])key(k,false);phase='idle';}
 function summary(){const f=intervals.filter(x=>x.t>resetAt), ds=f.map(x=>x.dt).sort((a,b)=>a-b), cp=rows.filter(x=>x.t>resetAt).map(x=>x.cpu).sort((a,b)=>a-b);return {cameraEstimate,adaptive:window.qaAdaptiveState,phase,ua:navigator.userAgent,dpr:devicePixelRatio,viewport:[innerWidth,innerHeight],canvas:{width:document.querySelector('canvas').width,height:document.querySelector('canvas').height,rect:document.querySelector('canvas').getBoundingClientRect().toJSON()},readyMs:readyAt,frames:ds.length,fps:ds.length?1000/(ds.reduce((a,b)=>a+b,0)/ds.length):null,frameP50:ds[Math.floor(ds.length*.5)],frameP95:ds[Math.floor(ds.length*.95)],frameP99:ds[Math.floor(ds.length*.99)],frameMax:ds[ds.length-1],callbackP50:cp[Math.floor(cp.length*.5)],callbackP95:cp[Math.floor(cp.length*.95)],callbackMax:cp[cp.length-1],wasmHeapBytes:instance?.Module?.HEAPU32?.buffer.byteLength,jsHeap:performance.memory?{used:performance.memory.usedJSHeapSize,total:performance.memory.totalJSHeapSize,limit:performance.memory.jsHeapSizeLimit}:null,audio:contexts.map(c=>({state:c.state,time:c.currentTime,rate:c.sampleRate})),textureUploads,audioSources,heapSamples,moduleKeys:instance?Object.keys(instance.Module).filter(x=>/memory|heap|load|time|audio/i.test(x)):[],resources:performance.getEntriesByType('resource').map(e=>({name:e.name,duration:e.duration,transfer:e.transferSize,encoded:e.encodedBodySize,decoded:e.decodedBodySize})),timeline};}
 document.addEventListener('DOMContentLoaded',()=>{
 const b=id=>document.getElementById(id); const canvas=document.querySelector('canvas');
 b('arm').onclick=()=>{window.qaArm=true;canvas.focus();};b('hold').onclick=()=>{canvas.focus();const k=b('qa-key').value;const token=++lastKeyRun;phase='key-'+k;key(k,true);setTimeout(()=>{if(token===lastKeyRun)key(k,false);},+b('qa-duration').value);};
 b('save-shot').onclick=()=>{fetch('/qa/results',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'screenshot',name:'browser-proof-'+Date.now()+'.jpg',data:'data:image/jpeg;base64,'+b('qa-shot').value})});b('qa-shot').value='';};b('stop').onclick=stop;b('capture').onclick=()=>captureRequested=true;
 b('reset-metrics').onclick=()=>{resetAt=performance.now();phase='measuring';timeline.push({kind:'reset',t:resetAt});};
 b('save').onclick=()=>fetch('/qa/results',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'metrics',summary:summary(),intervals,callbacks:rows})});
 for(const [id,w,h] of [['size16',960,540],['sizenarrow',600,600],['sizewide',1100,500]])b(id).onclick=()=>{canvas.style.width=w+'px';canvas.style.height=h+'px';timeline.push({kind:'resize',t:performance.now(),w,h});};
 for(const [id,dpr] of [['dpr1',1],['dpr2',2]])b(id).onclick=()=>{if(instance)instance.Module.devicePixelRatio=dpr;timeline.push({kind:'render-dpr',t:performance.now(),dpr});};
 b('replay').onclick=async()=>{stop();canvas.focus();const seq=await fetch('/qa/input-replay.json').then(r=>r.json()),token=++replayToken;phase='traversal';resetAt=performance.now();const t0=performance.now()+200;timeline.push({kind:'run-start',t:t0});let i=0;function tick(t){if(token!==replayToken)return;const dt=(t-t0)/1000;while(i<seq.length&&seq[i].t<=dt){key(seq[i].code,seq[i].down);i++;}if(i<seq.length)nativeRAF(tick);else{stop();timeline.push({kind:'run-end',t:performance.now()});}}nativeRAF(tick);};
 document.addEventListener('pointerdown',e=>timeline.push({t:performance.now(),kind:'pointer',target:e.target.id,x:e.clientX,y:e.clientY}));
 document.addEventListener('keydown',e=>{if(e.isTrusted)timeline.push({t:performance.now(),kind:'trusted-key',key:e.code});});
 setInterval(()=>{heapSamples.push({t:performance.now(),bytes:instance?.Module?.HEAPU32?.buffer.byteLength}); const s=summary();for(const k of ['resources','timeline','moduleKeys','audioSources','heapSamples','textureUploads'])delete s[k]; b('qa-status').textContent=JSON.stringify(s);},500);
 });
})();
